# Generated by Django 5.2.2 on 2025-06-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='original_url',
            field=models.URLField(help_text='Original URL to shorten', max_length=2000),
        ),
    ]
